spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog? serverTimezone=CST&useUnicode=true&characterEncoding=utf-8
    username : root
    password : qwer40103

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.jack: debug
  file:
    name: blog-dev.log
    path: log/